//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClangVSx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClangVSx.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        internal static string deAction {
            get {
                return ResourceManager.GetString("deAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-Ins.
        /// </summary>
        internal static string deAddins {
            get {
                return ResourceManager.GetString("deAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string deBuild {
            get {
                return ResourceManager.GetString("deBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klassendiagramm.
        /// </summary>
        internal static string deClass_Diagram {
            get {
                return ResourceManager.GetString("deClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string deCommunity {
            get {
                return ResourceManager.GetString("deCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten.
        /// </summary>
        internal static string deData {
            get {
                return ResourceManager.GetString("deData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank.
        /// </summary>
        internal static string deDatabase {
            get {
                return ResourceManager.GetString("deDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankdiagramm.
        /// </summary>
        internal static string deDatabase_Diagram {
            get {
                return ResourceManager.GetString("deDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuggen.
        /// </summary>
        internal static string deDebug {
            get {
                return ResourceManager.GetString("deDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramm.
        /// </summary>
        internal static string deDiagram {
            get {
                return ResourceManager.GetString("deDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string deEdit {
            get {
                return ResourceManager.GetString("deEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string deFile {
            get {
                return ResourceManager.GetString("deFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string deFormat {
            get {
                return ResourceManager.GetString("deFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmen.
        /// </summary>
        internal static string deFrames {
            get {
                return ResourceManager.GetString("deFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string deHelp {
            get {
                return ResourceManager.GetString("deHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        internal static string deImage {
            get {
                return ResourceManager.GetString("deImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string deLayout {
            get {
                return ResourceManager.GetString("deLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makros.
        /// </summary>
        internal static string deMacros {
            get {
                return ResourceManager.GetString("deMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        internal static string deProject {
            get {
                return ResourceManager.GetString("deProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string deQuery {
            get {
                return ResourceManager.GetString("deQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abfrage-Designer.
        /// </summary>
        internal static string deQuery_Designer {
            get {
                return ResourceManager.GetString("deQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umgestalten.
        /// </summary>
        internal static string deRefactor {
            get {
                return ResourceManager.GetString("deRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressourcen.
        /// </summary>
        internal static string deResources {
            get {
                return ResourceManager.GetString("deResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string deSchema {
            get {
                return ResourceManager.GetString("deSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formate.
        /// </summary>
        internal static string deStyles {
            get {
                return ResourceManager.GetString("deStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle.
        /// </summary>
        internal static string deTable {
            get {
                return ResourceManager.GetString("deTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabellen-Designer.
        /// </summary>
        internal static string deTable_Designer {
            get {
                return ResourceManager.GetString("deTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string deTeam {
            get {
                return ResourceManager.GetString("deTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testen.
        /// </summary>
        internal static string deTest {
            get {
                return ResourceManager.GetString("deTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string deTools {
            get {
                return ResourceManager.GetString("deTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht.
        /// </summary>
        internal static string deView {
            get {
                return ResourceManager.GetString("deView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster.
        /// </summary>
        internal static string deWindow {
            get {
                return ResourceManager.GetString("deWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string deXML {
            get {
                return ResourceManager.GetString("deXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addins.
        /// </summary>
        internal static string enAddins {
            get {
                return ResourceManager.GetString("enAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Diagram.
        /// </summary>
        internal static string enClass_Diagram {
            get {
                return ResourceManager.GetString("enClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string enCommunity {
            get {
                return ResourceManager.GetString("enCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Diagram.
        /// </summary>
        internal static string enDatabase_Diagram {
            get {
                return ResourceManager.GetString("enDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string enLayout {
            get {
                return ResourceManager.GetString("enLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string enMacros {
            get {
                return ResourceManager.GetString("enMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Designer.
        /// </summary>
        internal static string enQuery_Designer {
            get {
                return ResourceManager.GetString("enQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor.
        /// </summary>
        internal static string enRefactor {
            get {
                return ResourceManager.GetString("enRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string enResources {
            get {
                return ResourceManager.GetString("enResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Designer.
        /// </summary>
        internal static string enTable_Designer {
            get {
                return ResourceManager.GetString("enTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string enTeam {
            get {
                return ResourceManager.GetString("enTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string enTest {
            get {
                return ResourceManager.GetString("enTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string esAction {
            get {
                return ResourceManager.GetString("esAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementos.
        /// </summary>
        internal static string esAddins {
            get {
                return ResourceManager.GetString("esAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        internal static string esBuild {
            get {
                return ResourceManager.GetString("esBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrama de clase.
        /// </summary>
        internal static string esClass_Diagram {
            get {
                return ResourceManager.GetString("esClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidad.
        /// </summary>
        internal static string esCommunity {
            get {
                return ResourceManager.GetString("esCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos.
        /// </summary>
        internal static string esData {
            get {
                return ResourceManager.GetString("esData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de datos.
        /// </summary>
        internal static string esDatabase {
            get {
                return ResourceManager.GetString("esDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrama de base de datos.
        /// </summary>
        internal static string esDatabase_Diagram {
            get {
                return ResourceManager.GetString("esDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depurar.
        /// </summary>
        internal static string esDebug {
            get {
                return ResourceManager.GetString("esDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrama.
        /// </summary>
        internal static string esDiagram {
            get {
                return ResourceManager.GetString("esDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string esEdit {
            get {
                return ResourceManager.GetString("esEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string esFile {
            get {
                return ResourceManager.GetString("esFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        internal static string esFormat {
            get {
                return ResourceManager.GetString("esFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcos.
        /// </summary>
        internal static string esFrames {
            get {
                return ResourceManager.GetString("esFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        internal static string esHelp {
            get {
                return ResourceManager.GetString("esHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string esImage {
            get {
                return ResourceManager.GetString("esImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseño.
        /// </summary>
        internal static string esLayout {
            get {
                return ResourceManager.GetString("esLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string esMacros {
            get {
                return ResourceManager.GetString("esMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        internal static string esProject {
            get {
                return ResourceManager.GetString("esProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta.
        /// </summary>
        internal static string esQuery {
            get {
                return ResourceManager.GetString("esQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseñador de consultas.
        /// </summary>
        internal static string esQuery_Designer {
            get {
                return ResourceManager.GetString("esQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactorizar.
        /// </summary>
        internal static string esRefactor {
            get {
                return ResourceManager.GetString("esRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        internal static string esResources {
            get {
                return ResourceManager.GetString("esResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquema.
        /// </summary>
        internal static string esSchema {
            get {
                return ResourceManager.GetString("esSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilos.
        /// </summary>
        internal static string esStyles {
            get {
                return ResourceManager.GetString("esStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla.
        /// </summary>
        internal static string esTable {
            get {
                return ResourceManager.GetString("esTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseñador de tablas.
        /// </summary>
        internal static string esTable_Designer {
            get {
                return ResourceManager.GetString("esTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo.
        /// </summary>
        internal static string esTeam {
            get {
                return ResourceManager.GetString("esTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba.
        /// </summary>
        internal static string esTest {
            get {
                return ResourceManager.GetString("esTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        internal static string esTools {
            get {
                return ResourceManager.GetString("esTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string esView {
            get {
                return ResourceManager.GetString("esView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        internal static string esWindow {
            get {
                return ResourceManager.GetString("esWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string esXML {
            get {
                return ResourceManager.GetString("esXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string frAction {
            get {
                return ResourceManager.GetString("frAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compléments.
        /// </summary>
        internal static string frAddins {
            get {
                return ResourceManager.GetString("frAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        internal static string frBuild {
            get {
                return ResourceManager.GetString("frBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramme de classes.
        /// </summary>
        internal static string frClass_Diagram {
            get {
                return ResourceManager.GetString("frClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communauté.
        /// </summary>
        internal static string frCommunity {
            get {
                return ResourceManager.GetString("frCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données.
        /// </summary>
        internal static string frData {
            get {
                return ResourceManager.GetString("frData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données.
        /// </summary>
        internal static string frDatabase {
            get {
                return ResourceManager.GetString("frDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schéma de base de données.
        /// </summary>
        internal static string frDatabase_Diagram {
            get {
                return ResourceManager.GetString("frDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déboguer.
        /// </summary>
        internal static string frDebug {
            get {
                return ResourceManager.GetString("frDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schéma.
        /// </summary>
        internal static string frDiagram {
            get {
                return ResourceManager.GetString("frDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string frEdit {
            get {
                return ResourceManager.GetString("frEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        internal static string frFile {
            get {
                return ResourceManager.GetString("frFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string frFormat {
            get {
                return ResourceManager.GetString("frFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string frFrames {
            get {
                return ResourceManager.GetString("frFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string frHelp {
            get {
                return ResourceManager.GetString("frHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string frImage {
            get {
                return ResourceManager.GetString("frImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        internal static string frLayout {
            get {
                return ResourceManager.GetString("frLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string frMacros {
            get {
                return ResourceManager.GetString("frMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string frProject {
            get {
                return ResourceManager.GetString("frProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requête.
        /// </summary>
        internal static string frQuery {
            get {
                return ResourceManager.GetString("frQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepteur de requêtes.
        /// </summary>
        internal static string frQuery_Designer {
            get {
                return ResourceManager.GetString("frQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactoriser.
        /// </summary>
        internal static string frRefactor {
            get {
                return ResourceManager.GetString("frRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources.
        /// </summary>
        internal static string frResources {
            get {
                return ResourceManager.GetString("frResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schéma.
        /// </summary>
        internal static string frSchema {
            get {
                return ResourceManager.GetString("frSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string frStyles {
            get {
                return ResourceManager.GetString("frStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau.
        /// </summary>
        internal static string frTable {
            get {
                return ResourceManager.GetString("frTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepteur de tables.
        /// </summary>
        internal static string frTable_Designer {
            get {
                return ResourceManager.GetString("frTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to équipe.
        /// </summary>
        internal static string frTeam {
            get {
                return ResourceManager.GetString("frTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string frTest {
            get {
                return ResourceManager.GetString("frTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outils.
        /// </summary>
        internal static string frTools {
            get {
                return ResourceManager.GetString("frTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage.
        /// </summary>
        internal static string frView {
            get {
                return ResourceManager.GetString("frView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenêtre.
        /// </summary>
        internal static string frWindow {
            get {
                return ResourceManager.GetString("frWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string frXML {
            get {
                return ResourceManager.GetString("frXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azione.
        /// </summary>
        internal static string itAction {
            get {
                return ResourceManager.GetString("itAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componenti aggiuntivi.
        /// </summary>
        internal static string itAddins {
            get {
                return ResourceManager.GetString("itAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genera.
        /// </summary>
        internal static string itBuild {
            get {
                return ResourceManager.GetString("itBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramma classi.
        /// </summary>
        internal static string itClass_Diagram {
            get {
                return ResourceManager.GetString("itClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunità.
        /// </summary>
        internal static string itCommunity {
            get {
                return ResourceManager.GetString("itCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati.
        /// </summary>
        internal static string itData {
            get {
                return ResourceManager.GetString("itData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string itDatabase {
            get {
                return ResourceManager.GetString("itDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramma database.
        /// </summary>
        internal static string itDatabase_Diagram {
            get {
                return ResourceManager.GetString("itDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string itDebug {
            get {
                return ResourceManager.GetString("itDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramma.
        /// </summary>
        internal static string itDiagram {
            get {
                return ResourceManager.GetString("itDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string itEdit {
            get {
                return ResourceManager.GetString("itEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string itFile {
            get {
                return ResourceManager.GetString("itFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        internal static string itFormat {
            get {
                return ResourceManager.GetString("itFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string itFrames {
            get {
                return ResourceManager.GetString("itFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string itHelp {
            get {
                return ResourceManager.GetString("itHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immagine.
        /// </summary>
        internal static string itImage {
            get {
                return ResourceManager.GetString("itImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string itLayout {
            get {
                return ResourceManager.GetString("itLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string itMacros {
            get {
                return ResourceManager.GetString("itMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progetto.
        /// </summary>
        internal static string itProject {
            get {
                return ResourceManager.GetString("itProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string itQuery {
            get {
                return ResourceManager.GetString("itQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progettazione query.
        /// </summary>
        internal static string itQuery_Designer {
            get {
                return ResourceManager.GetString("itQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effettua refactoring.
        /// </summary>
        internal static string itRefactor {
            get {
                return ResourceManager.GetString("itRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risorse.
        /// </summary>
        internal static string itResources {
            get {
                return ResourceManager.GetString("itResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string itSchema {
            get {
                return ResourceManager.GetString("itSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stili.
        /// </summary>
        internal static string itStyles {
            get {
                return ResourceManager.GetString("itStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabella.
        /// </summary>
        internal static string itTable {
            get {
                return ResourceManager.GetString("itTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progettazione tabelle.
        /// </summary>
        internal static string itTable_Designer {
            get {
                return ResourceManager.GetString("itTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string itTeam {
            get {
                return ResourceManager.GetString("itTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prova.
        /// </summary>
        internal static string itTest {
            get {
                return ResourceManager.GetString("itTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strumenti.
        /// </summary>
        internal static string itTools {
            get {
                return ResourceManager.GetString("itTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza.
        /// </summary>
        internal static string itView {
            get {
                return ResourceManager.GetString("itView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finestra.
        /// </summary>
        internal static string itWindow {
            get {
                return ResourceManager.GetString("itWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string itXML {
            get {
                return ResourceManager.GetString("itXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アドイン.
        /// </summary>
        internal static string jaAddins {
            get {
                return ResourceManager.GetString("jaAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビルド.
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クラス ダイアグラム.
        /// </summary>
        internal static string jaClass_Diagram {
            get {
                return ResourceManager.GetString("jaClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コミュニティ.
        /// </summary>
        internal static string jaCommunity {
            get {
                return ResourceManager.GetString("jaCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース.
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース ダイアグラム.
        /// </summary>
        internal static string jaDatabase_Diagram {
            get {
                return ResourceManager.GetString("jaDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバッグ.
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダイアグラム.
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書式.
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フレーム.
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イメージ.
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト.
        /// </summary>
        internal static string jaLayout {
            get {
                return ResourceManager.GetString("jaLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マクロ.
        /// </summary>
        internal static string jaMacros {
            get {
                return ResourceManager.GetString("jaMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクト.
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クエリ.
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クエリ デザイナ.
        /// </summary>
        internal static string jaQuery_Designer {
            get {
                return ResourceManager.GetString("jaQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リファクタ.
        /// </summary>
        internal static string jaRefactor {
            get {
                return ResourceManager.GetString("jaRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リソース.
        /// </summary>
        internal static string jaResources {
            get {
                return ResourceManager.GetString("jaResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキーマ.
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタイル.
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーブル.
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーブル デザイナ.
        /// </summary>
        internal static string jaTable_Designer {
            get {
                return ResourceManager.GetString("jaTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チーム.
        /// </summary>
        internal static string jaTeam {
            get {
                return ResourceManager.GetString("jaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト.
        /// </summary>
        internal static string jaTest {
            get {
                return ResourceManager.GetString("jaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ.
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업.
        /// </summary>
        internal static string koAction {
            get {
                return ResourceManager.GetString("koAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가 기능.
        /// </summary>
        internal static string koAddins {
            get {
                return ResourceManager.GetString("koAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 빌드.
        /// </summary>
        internal static string koBuild {
            get {
                return ResourceManager.GetString("koBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클래스 다이어그램.
        /// </summary>
        internal static string koClass_Diagram {
            get {
                return ResourceManager.GetString("koClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 커뮤니티.
        /// </summary>
        internal static string koCommunity {
            get {
                return ResourceManager.GetString("koCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터.
        /// </summary>
        internal static string koData {
            get {
                return ResourceManager.GetString("koData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터베이스.
        /// </summary>
        internal static string koDatabase {
            get {
                return ResourceManager.GetString("koDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터베이스 다이어그램.
        /// </summary>
        internal static string koDatabase_Diagram {
            get {
                return ResourceManager.GetString("koDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 디버그.
        /// </summary>
        internal static string koDebug {
            get {
                return ResourceManager.GetString("koDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다이어그램.
        /// </summary>
        internal static string koDiagram {
            get {
                return ResourceManager.GetString("koDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 편집.
        /// </summary>
        internal static string koEdit {
            get {
                return ResourceManager.GetString("koEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일.
        /// </summary>
        internal static string koFile {
            get {
                return ResourceManager.GetString("koFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서식.
        /// </summary>
        internal static string koFormat {
            get {
                return ResourceManager.GetString("koFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프레임.
        /// </summary>
        internal static string koFrames {
            get {
                return ResourceManager.GetString("koFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 도움말.
        /// </summary>
        internal static string koHelp {
            get {
                return ResourceManager.GetString("koHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미지.
        /// </summary>
        internal static string koImage {
            get {
                return ResourceManager.GetString("koImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 레이아웃.
        /// </summary>
        internal static string koLayout {
            get {
                return ResourceManager.GetString("koLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 매크로.
        /// </summary>
        internal static string koMacros {
            get {
                return ResourceManager.GetString("koMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로젝트.
        /// </summary>
        internal static string koProject {
            get {
                return ResourceManager.GetString("koProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿼리.
        /// </summary>
        internal static string koQuery {
            get {
                return ResourceManager.GetString("koQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿼리 디자이너.
        /// </summary>
        internal static string koQuery_Designer {
            get {
                return ResourceManager.GetString("koQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리팩터링.
        /// </summary>
        internal static string koRefactor {
            get {
                return ResourceManager.GetString("koRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스.
        /// </summary>
        internal static string koResources {
            get {
                return ResourceManager.GetString("koResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스키마.
        /// </summary>
        internal static string koSchema {
            get {
                return ResourceManager.GetString("koSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스타일.
        /// </summary>
        internal static string koStyles {
            get {
                return ResourceManager.GetString("koStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 테이블.
        /// </summary>
        internal static string koTable {
            get {
                return ResourceManager.GetString("koTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 테이블 디자이너.
        /// </summary>
        internal static string koTable_Designer {
            get {
                return ResourceManager.GetString("koTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팀.
        /// </summary>
        internal static string koTeam {
            get {
                return ResourceManager.GetString("koTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 테스트.
        /// </summary>
        internal static string koTest {
            get {
                return ResourceManager.GetString("koTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 도구.
        /// </summary>
        internal static string koTools {
            get {
                return ResourceManager.GetString("koTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 뷰.
        /// </summary>
        internal static string koView {
            get {
                return ResourceManager.GetString("koView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 창.
        /// </summary>
        internal static string koWindow {
            get {
                return ResourceManager.GetString("koWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string koXML {
            get {
                return ResourceManager.GetString("koXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        internal static string zh_CHSAction {
            get {
                return ResourceManager.GetString("zh-CHSAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外接程序.
        /// </summary>
        internal static string zh_CHSAddins {
            get {
                return ResourceManager.GetString("zh-CHSAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成.
        /// </summary>
        internal static string zh_CHSBuild {
            get {
                return ResourceManager.GetString("zh-CHSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类关系图.
        /// </summary>
        internal static string zh_CHSClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社区.
        /// </summary>
        internal static string zh_CHSCommunity {
            get {
                return ResourceManager.GetString("zh-CHSCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据.
        /// </summary>
        internal static string zh_CHSData {
            get {
                return ResourceManager.GetString("zh-CHSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库.
        /// </summary>
        internal static string zh_CHSDatabase {
            get {
                return ResourceManager.GetString("zh-CHSDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库关系图.
        /// </summary>
        internal static string zh_CHSDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试.
        /// </summary>
        internal static string zh_CHSDebug {
            get {
                return ResourceManager.GetString("zh-CHSDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关系图.
        /// </summary>
        internal static string zh_CHSDiagram {
            get {
                return ResourceManager.GetString("zh-CHSDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string zh_CHSEdit {
            get {
                return ResourceManager.GetString("zh-CHSEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        internal static string zh_CHSFile {
            get {
                return ResourceManager.GetString("zh-CHSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式.
        /// </summary>
        internal static string zh_CHSFormat {
            get {
                return ResourceManager.GetString("zh-CHSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框架.
        /// </summary>
        internal static string zh_CHSFrames {
            get {
                return ResourceManager.GetString("zh-CHSFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string zh_CHSHelp {
            get {
                return ResourceManager.GetString("zh-CHSHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像.
        /// </summary>
        internal static string zh_CHSImage {
            get {
                return ResourceManager.GetString("zh-CHSImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 布局.
        /// </summary>
        internal static string zh_CHSLayout {
            get {
                return ResourceManager.GetString("zh-CHSLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宏.
        /// </summary>
        internal static string zh_CHSMacros {
            get {
                return ResourceManager.GetString("zh-CHSMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目.
        /// </summary>
        internal static string zh_CHSProject {
            get {
                return ResourceManager.GetString("zh-CHSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        internal static string zh_CHSQuery {
            get {
                return ResourceManager.GetString("zh-CHSQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询设计器.
        /// </summary>
        internal static string zh_CHSQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHSQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重构.
        /// </summary>
        internal static string zh_CHSRefactor {
            get {
                return ResourceManager.GetString("zh-CHSRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源.
        /// </summary>
        internal static string zh_CHSResources {
            get {
                return ResourceManager.GetString("zh-CHSResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 架构.
        /// </summary>
        internal static string zh_CHSSchema {
            get {
                return ResourceManager.GetString("zh-CHSSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式.
        /// </summary>
        internal static string zh_CHSStyles {
            get {
                return ResourceManager.GetString("zh-CHSStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表.
        /// </summary>
        internal static string zh_CHSTable {
            get {
                return ResourceManager.GetString("zh-CHSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表设计器.
        /// </summary>
        internal static string zh_CHSTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHSTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作组.
        /// </summary>
        internal static string zh_CHSTeam {
            get {
                return ResourceManager.GetString("zh-CHSTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试.
        /// </summary>
        internal static string zh_CHSTest {
            get {
                return ResourceManager.GetString("zh-CHSTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        internal static string zh_CHSTools {
            get {
                return ResourceManager.GetString("zh-CHSTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图.
        /// </summary>
        internal static string zh_CHSView {
            get {
                return ResourceManager.GetString("zh-CHSView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口.
        /// </summary>
        internal static string zh_CHSWindow {
            get {
                return ResourceManager.GetString("zh-CHSWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string zh_CHSXML {
            get {
                return ResourceManager.GetString("zh-CHSXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作.
        /// </summary>
        internal static string zh_CHTAction {
            get {
                return ResourceManager.GetString("zh-CHTAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增益集.
        /// </summary>
        internal static string zh_CHTAddins {
            get {
                return ResourceManager.GetString("zh-CHTAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建置.
        /// </summary>
        internal static string zh_CHTBuild {
            get {
                return ResourceManager.GetString("zh-CHTBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 類別圖表.
        /// </summary>
        internal static string zh_CHTClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社群.
        /// </summary>
        internal static string zh_CHTCommunity {
            get {
                return ResourceManager.GetString("zh-CHTCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料.
        /// </summary>
        internal static string zh_CHTData {
            get {
                return ResourceManager.GetString("zh-CHTData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料庫.
        /// </summary>
        internal static string zh_CHTDatabase {
            get {
                return ResourceManager.GetString("zh-CHTDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料庫圖表.
        /// </summary>
        internal static string zh_CHTDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偵錯.
        /// </summary>
        internal static string zh_CHTDebug {
            get {
                return ResourceManager.GetString("zh-CHTDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖表.
        /// </summary>
        internal static string zh_CHTDiagram {
            get {
                return ResourceManager.GetString("zh-CHTDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string zh_CHTEdit {
            get {
                return ResourceManager.GetString("zh-CHTEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案.
        /// </summary>
        internal static string zh_CHTFile {
            get {
                return ResourceManager.GetString("zh-CHTFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式.
        /// </summary>
        internal static string zh_CHTFormat {
            get {
                return ResourceManager.GetString("zh-CHTFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框架.
        /// </summary>
        internal static string zh_CHTFrames {
            get {
                return ResourceManager.GetString("zh-CHTFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 說明.
        /// </summary>
        internal static string zh_CHTHelp {
            get {
                return ResourceManager.GetString("zh-CHTHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影像.
        /// </summary>
        internal static string zh_CHTImage {
            get {
                return ResourceManager.GetString("zh-CHTImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置.
        /// </summary>
        internal static string zh_CHTLayout {
            get {
                return ResourceManager.GetString("zh-CHTLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巨集.
        /// </summary>
        internal static string zh_CHTMacros {
            get {
                return ResourceManager.GetString("zh-CHTMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專案.
        /// </summary>
        internal static string zh_CHTProject {
            get {
                return ResourceManager.GetString("zh-CHTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢.
        /// </summary>
        internal static string zh_CHTQuery {
            get {
                return ResourceManager.GetString("zh-CHTQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢設計工具.
        /// </summary>
        internal static string zh_CHTQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHTQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重整.
        /// </summary>
        internal static string zh_CHTRefactor {
            get {
                return ResourceManager.GetString("zh-CHTRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資源.
        /// </summary>
        internal static string zh_CHTResources {
            get {
                return ResourceManager.GetString("zh-CHTResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結構描述.
        /// </summary>
        internal static string zh_CHTSchema {
            get {
                return ResourceManager.GetString("zh-CHTSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 樣式.
        /// </summary>
        internal static string zh_CHTStyles {
            get {
                return ResourceManager.GetString("zh-CHTStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料表.
        /// </summary>
        internal static string zh_CHTTable {
            get {
                return ResourceManager.GetString("zh-CHTTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料表設計工具.
        /// </summary>
        internal static string zh_CHTTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHTTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小組.
        /// </summary>
        internal static string zh_CHTTeam {
            get {
                return ResourceManager.GetString("zh-CHTTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測試.
        /// </summary>
        internal static string zh_CHTTest {
            get {
                return ResourceManager.GetString("zh-CHTTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        internal static string zh_CHTTools {
            get {
                return ResourceManager.GetString("zh-CHTTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢視.
        /// </summary>
        internal static string zh_CHTView {
            get {
                return ResourceManager.GetString("zh-CHTView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 視窗.
        /// </summary>
        internal static string zh_CHTWindow {
            get {
                return ResourceManager.GetString("zh-CHTWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string zh_CHTXML {
            get {
                return ResourceManager.GetString("zh-CHTXML", resourceCulture);
            }
        }
    }
}
